### ISSUE TITLE
codepen.io

### ISSUE THREAD

**Issue by jt3k** [kizu/bemto#100]
is there a way to use bemto in codepen editor ?
<img width="259" alt="image" src="https://user-images.githubusercontent.com/1261240/218286437-4d74486b-8df0-48ff-af46-f896713d0f8b.png">

**Comment by kizu** [comment]
Not really — from what I know, it doesn't support adding packages that can be used for pug. I imagine main way to achieve something akin to the codepen experience with it (live editable with a preview) is to set up something like a codesandbox/stackblitz.
