### ISSUE TITLE
Setting for allowing nested elements

### ISSUE THREAD

**Issue by kizu** [kizu/bemto#20]
Moved from #4

Right now the elements don't create the block scope, however there are a lot of people who use it this way, so we could add an ability to do so.

Also, there'd be a need to “jump” higher to blocks etc. by adding more element delimiters at the start.

**Comment by acjay** [comment]
It's not a good idea to have elements create their own block scopes in general. BEM really shines when elements are "portable", meaning that you can move them around and change their nesting without modifying the styles.

But an important BEM concept is to allow for the same tag to be an element of a block and its own block root:

```html
<div class="my-big-component">
  <div class="my-big-component__submit-control special-button">
    <div class="special-button__label"></div>
    <div class="special-button__other-label"></div>
  </div>
</div>
```

**Comment by ocoka** [comment]
But for now we already can make this:
```jade
+b.some-block
  +b.scoped-elt.__element
    +e.sub-element
```
And we will get:
```html
<div class="some-block">
  <div class="scoped-elt some-block__element">
      <span class="scoped-elt__sub-element"
```

**Comment by kizu** [comment]
The basics for this was made in rc-1.0 using a special option and a syntax for making an element to be a root of the following elements:

``` jade
- set_bemto_settings({ flat_elements: false })

+b.foo
  +e.bar__
    +e.taz
```

producing

``` html
<div class="foo">
  <div class="foo__bar">
    <div class="foo__bar__taz">
    </div>
  </div>
</div>
```

There are still some cases for elements of elements left, but they'll be implemented in later versions.
