### ISSUE TITLE
Закрывающий слеш у input, img и т.п. 

### ISSUE THREAD

**Issue by Leolik** [kizu/bemto#36]
Можно ли как-то отключить вставку закрывающего тега для input, img и т.п. при использовании bemto?

Пример:
```
+b.form-item
    +e('input')
    input(type="text")
```
разворачивается в:
```
<div class="form-item">
    <input type="text"/>
    <input type="text">
</div>
```

**Comment by kizu** [comment]
Это баг Jade, заключающийся в том, что у них странно работает проверка на доктайп, которая отвечает за слеш у самозакрывающихся тегов.

 1.0 я попробую обойти этот баг.
