### ISSUE TITLE
Bemto lost js context when using extends

### ISSUE THREAD

**Issue by thekip** [kizu/bemto#42]
Create a layout file:
```jade
block header
  di-panel-header(
  close-callback="details.closeDetails()"
  title="{{ details.selectedEvent.st + details.selectedEvent.loc_tzs | timeUTC:{format: 'ddd, DD MMM, HH:mm'} }}"
  )

block body
  +b.event-details.scroll-area
    .scroll-area__helper.scroll-area__helper--venue-details
```

Create a view wich extends a layout:

```jade
extends ./layout.jade

append body
  di-point-header(point="selectedEvent.getPointInfo()")

  +b.point-details(ng-if="selectedEvent.description")
    +e.row.--column.--contacts
      +e('h4').caption Описание встречи

      +e.misc-info.--location
        span(ng-bind="selectedEvent.description")

  di-place-info(point="selectedEvent.getPointInfo()")
```

And get the error: 
```jade
    168|
    169|     if !isElement
  > 170|       - bemto_chain[bemto_chain.length] = bemto_block
    171|       - bemto_classes[0] = bemto_classes[0]
    172|     else
    173|       - bemto_classes[0] = bemto_chain[bemto_chain.length-1] + bemto_settings_element + bemto_classes[0]

Cannot read property 'length' of undefined
```

I tried to debug a little bit, and recognize that global variables `bemto_chain` and `bemto_chain_contexts` is undefined when error occurs.

**Comment by thekip** [comment]
I've made a dirty workaround, if add this code before 169 line, error will disappear.
```jade
    if (!bemto_chain)
      - bemto_chain = [];

    if (!bemto_chain_contexts)
      - bemto_chain_contexts = ['block'];
```

But actually I don't understand what exactly happend, that's why I don't recommend this solution.

**Comment by thekip** [comment]
workaround doesn't work. Error will disappear but, bemto works incorrect (undefined instead of block name)

**Comment by jt3k** [comment]
I have the same error

**Comment by thekip** [comment]
This error appears because mixin have to be included in layout file as well. 

Just add mixin to layout file.

**Comment by kizu** [comment]
Yeah, I'm aware of this problem, but I'm not sure it is fixable, as that's how layouts work in Jade :( I'll look into it in the future, but can't promise anything.

**Comment by glebmachine** [comment]
Come on, include bemto into your layout file, or use it incide block element

**Comment by kizu** [comment]
Right, bemto should be included in the layout file, this way everything would work just fine.
