### ISSUE TITLE
Can't use button tag with type attribute

### ISSUE THREAD

**Issue by ocoka** [kizu/bemto#43]
The issue is that the **input** is an empty tag, and when we want to use some content inside button
we should to use a **button** tag,
but it is not possible to use **button** tag with a **type** attribute in **bemto**.
The reason to use **type** attribute is in case when we have many button in a form, and to
set button that is do submit we have to use **type** attribute (type=button and type=submit)

**Comment by kizu** [comment]
Thanks for the report! This issue was fixed in a `rc-1.0` branch and would be released as a part of 1.0 (no due date though yet, hopefully somewhere in November).
