### ISSUE TITLE
Multiple modifiers not added properly when certain separators defined

### ISSUE THREAD

**Issue by jonscottclark** [kizu/bemto#44]
Hey @kizu,

First, thanks for your mixin. It's really made the transition to BEM syntax a lot easier.

I am using these settings:

```jade
- bemto_settings_prefix = ''
- bemto_settings_element = '-'
- bemto_settings_modifier = '--'
```

I try your example, changing the syntax to match my settings:

```jade
+b.block--foo.--bar.--baz
  +e.element--type_lol.--mode_moddy
```

But it renders like this:
```html
<div class="block block--bar block--baz block--foo">
  <div class="block--mode_moddy block-element block-element--type_lol">
</div>
```

As you can see, the "mode_moddy" modifier class is being added as a modifier of the parent block, I think because the mixin sees the first "-" character, and then uses the rest of the string ("-mode_moddy") as an element name, placing it first in the class list.

If I change my element separator to two underscores, like so: `- bemto_settings_element = '__'`, and then run the test again, it returns as expected:

```html
<div class="block block--bar block--baz block--foo">
  <div class="block__element block__element--mode_moddy block__element--type_lol">
</div>
```

I guess the problem is that I am only using hyphens in my separator settings. While this isn't the official BEM syntax, a few people suggest using a syntax with *just* hyphens, like I'm trying to do:
- http://nicolasgallagher.com/about-html-semantics-front-end-architecture/#structured-class-names
- https://www.youtube.com/watch?v=NrHVjxLpzXA&feature=youtu.be&t=17m58s

I'm not able to diagnose where in the mixin I should look to get this working.. likely in some regex somewhere.. but I figured I should bring it to your attention in case there is an easy fix to allow some more flexibility with the separator options.

**Comment by jonscottclark** [comment]
I'm sorry that I didn't realize you have addressed the possibility of using these different separators in your README... but it seems like the problem just lies with the nested element. The initial block handles things just fine.

I tried looking through the source to understand things but didn't get too far :(

Thank you for any help or clarification you can provide, I hope I'm not missing anything obvious!

**Comment by kizu** [comment]
Yep, this is a bug, mode-moddy in that case should always be attached to the element.
