### ISSUE TITLE
Make different settings for the jade bem delimiters syntax and output one

### ISSUE THREAD

**Issue by kizu** [kizu/bemto#47]
Right now the syntax settings (`__` vs `-` etc.) work both for defining stuff at jade level and how those classes would be outputted in HTML. It would be nice to separate those, so it would be possible to change how the output would look like.

**Comment by jonscottclark** [comment]
Ambitious! When could this be a use case, wouldn't it potentially confuse a maintainer if they couldn't trace why it's different in the output? Though I can see the other argument as well, if you had one developer writing jade and another doing the styling, but both had their preferred syntax. Thanks for your work on this, I am using this a lot and will do what I can to help.
