### ISSUE TITLE
How to add mix to an element?

### ISSUE THREAD

**Issue by f0rmat1k** [kizu/bemto#68]
When i try do it using attribute `class`, i got `block-name__mix-name` instead of just `mix-name`. Is it possible?

**Comment by f0rmat1k** [comment]
Interesting moment. When i add second mix, it works fine. Example:
```jade
    +b.change
        +e('form')(class="test simple-form").form
 ```jade

Turns into 
```html
<div class="change">
    <form class="change__test form simple-form">
```

**Comment by kizu** [comment]
I'm not sure I've understood what you're trying to do in the opening post.

There is no difference for mixins where the classes are going from, the dot syntax is just a shortcut, so `+e(class="test simple-form")` is equal to the `+e.test.simple-form` — bemto treats the first class as the element's name regardless of the used syntax.

If you need more than one element to be mixed, you can use the `__` prefix syntax for those classes, so, for example, if you need to mix both `test` and `simple-form` on element, but need `form` to stay as is, you can write it this way: `+e.test.__simple-form.form` If you need to have the classes in the attribute syntax, but also have a class that should become an element's name, you can write the dot syntax _before_ the attributes: `+e('form').form(class="test simple-form")`

(of course, everything I'm talking about now is actual for 1.0.0 version)

**Comment by f0rmat1k** [comment]
Understood, thank you.
