### ISSUE TITLE
Ability to turn off inline element detection and context

### ISSUE THREAD

**Issue by jonscottclark** [kizu/bemto#74]
Sometimes I have `<a>` elements that I've set to be `display: block`, but bemto assumes it's an inline element, so any child elements that I generate using the `+e` mixin end up as `<span>` elements and not the default `<div>`. Could there be a setting to disable this? I understand that it's a smart thing to include to help people, but most of the time, personally, it just gets in the way.

Thoughts, @kizu ?

**Comment by kizu** [comment]
That's possible right now, both on the per-element level (the [documented](https://github.com/kizu/bemto#redefining-tags-metadata) way) and on global level (not documented as may change in the future) look at https://github.com/kizu/bemto/pull/61#issuecomment-177940468 and

**Comment by jonscottclark** [comment]
Sweet, thank you! Sorry for not searching the issues :)
