### ISSUE TITLE
SUIT CSS support

### ISSUE THREAD

**Issue by FranzSkuffka** [kizu/bemto#76]
SUIT and BEM are pretty close to each other, is it possible to create SUIT-style syntax with this.
https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md

**Comment by kizu** [comment]
Hi, what have you tried? If what you're asking is using SUIT's naming convention, it is possible, see [readme for settings](https://github.com/kizu/bemto#settings).

For example,

``` jade
-
  set_bemto_settings({
    element: '-',
    modifier: '--'
  })

+b.ComponentName.is-stateOfComponent
  +e.descendentName--modifierName
```

would be rendered as 

``` html
<div class="ComponentName is-stateOfComponent">
  <div class="ComponentName-descendentName ComponentName-descendentName--modifierName">
  </div>
</div>
```

**Comment by FranzSkuffka** [comment]
Great, thank you very much. And sorry for asking stupid questions. I did not look closely enough. 
Should I create a PR from your example?
