### ISSUE TITLE
Форматировать отступ в выхлопе

### ISSUE THREAD

**Issue by slavikse** [kizu/bemto#78]
Добрый день!
Если еще поддерживаете, то:
Просьба добавить в быстрый конфиг форматирование отступов в нужное количество пробелов.
К примеру по умолчанию, сделать 2 пробела :)
Сейчас же, выглядит просто ужасно :(
<a href="http://www.zimagez.com/zimage/screenshot-05042016-002739.php">
  <img src="http://www.zimagez.com/miniature/screenshot-05042016-002739.php" />
</a>
<a href="http://www.zimagez.com/zimage/screenshot-05042016-002451.php">
  <img src="http://www.zimagez.com/miniature/screenshot-05042016-002451.php" />
</a>
Спасибо!

**Comment by kizu** [comment]
У меня не получается воспроизвести, в моём окружении код в примере компилируется в 

```

<div class="test">
  <div class="test__title">title
  </div>
  <div class="section sec">
    <div class="section__one">one
    </div>
    <div class="section__two section__logic-js">two
    </div>
  </div>
</div>
```

Какая версия bemto и jade?

**Comment by kizu** [comment]
Ну и, вообще, это точно не задача bemto управлять отступами — это должно быть на стороне jade автоматически происходить в зависимости от наличия флага `pretty` в опциях. Так что даже если проблема есть — вряд ли мы тут сможем это поправить.

**Comment by slavikse** [comment]
Как странно. Ну ладно, уже не пользуюсь bemto
