### ISSUE TITLE
Add some smart mixing

### ISSUE THREAD

**Issue by kizu** [kizu/bemto#8]
Right now it's not that easy to mix blocks. It would be nice to have a way to somehow declare mixings of blocks or elements in a way where all the bemto features would work for everyone.

**Comment by ainop** [comment]
You say “not that easy”. Is there some workaround for mixing elements on blocks?

**Comment by kizu** [comment]
Elements for the same block could be somehow mixed, but other blocks would need to be written fully:

``` jade
+b.block1
  +e.el1.__el2.block2.block2__el
```

**Comment by kizu** [comment]
Closing in favor of #46
