### ISSUE TITLE
Pug support any time soon?

### ISSUE THREAD

**Issue by name-k** [kizu/bemto#81]
As you probably know, jade became pug and `include` now works only with `.pug` extension.
Changing bemto files extension does not do the trick, same code, that works with jade, does not work with pug compiler. Probably the reason for that a version update to `2.0.0-alpha3`. 

So, will there be pug support any time soon? Or after pug stable release?

**Comment by glebmachine** [comment]
You need to replace .jade file extension to .pug
Soon, pug community will add legacy support (on 2.0.0 milestone)

For now, rename files, or use my temp fork: https://github.com/glebmachine/bemto

**Comment by kizu** [comment]
Pug support is planned, of course.

**Comment by kandrianov** [comment]
Only one problem with switching to pug - its modifiers with '--' for separator setting, cause ".--modifier" is not a valid classname. And we can do nothing with it.
Can we avoid using this? it's not official syntax, right?

**Comment by kizu** [comment]
@kandrianov Can you give me a link to the issue in Pug's repo about this? Why we can do nothing about it?

In the worst case, we still could use the `._modifier` syntax I guess, and reassign it in the output to `--` when needed. But I think it would be better to talk with Pug developers if there is an issue/conflict with the classnames starting with `-`.

**Comment by jonscottclark** [comment]
Hey @kizu, ran into this today when I was trying to migrate to Pug.

Here's the line in **pug-lexer** that throws the error: https://github.com/pugjs/pug-lexer/blob/master/index.js#L406-L408

**Comment by kizu** [comment]
Just released `bemto.pug@2.0.0` in npm, `bemto.jade` wouldn't be updated now. If someone would have issues with it, feel free to fill new issues up!

**Comment by jonscottclark** [comment]
@kizu That's amazing! This means that I will actually convert to Pug fully now :) I'll try out bemto.pug and report anything I find.
