### ISSUE TITLE
feature requirement

### ISSUE THREAD

**Issue by QuietJam** [kizu/bemto#82]
HI,I met some trouble,and i con't find solutions after reading the document. for example:
how to implement this code below:
//-----
div.widget-form
&nbsp;&nbsp;&nbsp;&nbsp;div.widget-form__selectbar.widget-selection
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;span.widget-selection__item something
//-------
the question is '.widget-selection' tag is a block but an element too,it has an alias named selectbar rendered by it's parent block 'widget-form'.
At present i don't know how to implement that by using bemto,can you help me? thanks very much!
ps. I don't want to write 'widget-form__selectbar' directly because of name 'widget-form' will be change at any time and name 'selectbar' will not change!

**Comment by kizu** [comment]
Hi, I think the following code would help you:

``` jade
+b.widget-form
  +e.selectbar.widget-selection__
    +e.SPAN.item something
```

This is a documented hehaviour, see https://github.com/kizu/bemto#context-of-the-element

**Comment by QuietJam** [comment]
ah,I'm so careless :(
