### ISSUE TITLE
Add setting for delimiter of class names.

### ISSUE THREAD

**Issue by pickmecoach** [kizu/bemto#87]
It would be handy in some cases if I could choose class names delimiter option too, i.e. output could be something like this:
`block | block_modifier--one | block_modifier--two`

**Comment by jt3k** [comment]
I'm not sure I understood you correctly.
Have you looked [here](https://github.com/kizu/bemto/blob/master/lib/settings.jade#L8) ?

**Comment by pickmecoach** [comment]
Well, I mean delimiter _between_ class names:
`block `**|**` block_modifier--one `**|**` block_modifier--two`
or may be like this:
`block `**//**` block_modifier--one `**//**` block_modifier--two`
This cannot be customized because several class names in the end of the story will be joined by space [in this line](https://github.com/kizu/bemto/blob/master/lib/bemto.jade#L129). Or did I missed smth?

**Comment by jt3k** [comment]
ok I understand u
May I ask what problem you intend to solve ?

**Comment by pickmecoach** [comment]
[it's not a problem](https://beneverard.co.uk/blog/using-slashes-within-the-html-class-attribute/), actually.
