### ISSUE TITLE
Перевод bemto в pug

### ISSUE THREAD

**Issue by mikaspell** [kizu/bemto#89]
Собственно весь вопрос в сабдже

**Comment by jt3k** [comment]
если вы про поддержку бемту в pug, то есть уже такой ишьюс https://github.com/kizu/bemto/issues/81
вкратце -- в pug зачемто убрали поддержку цсс-классов начинающихся  с `_` и стали невозможны конструкции типа +mixinn.lolo._lala

**Comment by mikaspell** [comment]
Сори за копию, смотрел и не увидел
