### ISSUE TITLE
Блок и элемент 2в1.

### ISSUE THREAD

**Issue by k26Skunk** [kizu/bemto#98]
Существует ли синтаксис для определения тега и как блока, и как элемента?
Ничего лучше не придумал, но написание полного класса элемента выглядит как-то не очень.
+b.HEADER.header
....+e.topline
........+e.wrap
............+b.logo.A(href="main.html" class="header__logo")
................img(src="../img/svg/logo.svg")
....+e.bottomline
........+e.wrap

**Comment by tabrisov** [comment]
+b.HEADER.header
...+e.top
......+e.logo.logo__ = "header__logo logo"
.........img(src="") = "logo__src"

**Comment by k26Skunk** [comment]
> +b.HEADER.header
> ...+e.top
> ......+e.logo.logo__ = "header__logo logo"
> .........img(src="") = "logo__src"

Спасибо, работает, только запись тогда лучше изменить на:
+b.logo.__logo.A(href="main.html") чтобы после компиляции класс блока стоял на первом месте.
